server.port=8080

spring.application.name=bfhl

# User Identity Config
app.user.full-name=ankit bansal
app.user.dob=15072005
app.user.email=bansalankit1575@gmail.com
app.user.roll-number=2310992106

# Jackson settings
spring.jackson.default-property-inclusion=non_null

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs
